<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::insert([
            // Rempah-Rempah/Herbal
            [
                'nama' => 'Benih Cabai Rawit',
                'jenis_kategori' => 'Rempah-Rempah/Herbal',
                'deskripsi' => 'Isi 50 butir, cocok untuk pekarangan rumah.',
                'jumlah_biji' => 50,
                'berat_bersih' => '50gr',
                'stok' => 100,
                'harga' => 15000,
                'gambar' => 'cabai_rawit.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Benih Jahe Merah',
                'jenis_kategori' => 'Rempah-Rempah/Herbal',
                'deskripsi' => 'Benih jahe merah, cocok untuk minuman herbal.',
                'jumlah_biji' => 40,
                'berat_bersih' => '40gr',
                'stok' => 80,
                'harga' => 18000,
                'gambar' => 'jahe_merah.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Benih Kunyit',
                'jenis_kategori' => 'Rempah-Rempah/Herbal',
                'deskripsi' => 'Benih kunyit kuning, segar dan berkualitas.',
                'jumlah_biji' => 35,
                'berat_bersih' => '35gr',
                'stok' => 60,
                'harga' => 14000,
                'gambar' => 'kunyit.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Benih Temulawak',
                'jenis_kategori' => 'Rempah-Rempah/Herbal',
                'deskripsi' => 'Benih temulawak segar, cocok untuk jamu.',
                'jumlah_biji' => 30,
                'berat_bersih' => '30gr',
                'stok' => 50,
                'harga' => 16000,
                'gambar' => 'temulawak.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Benih Herbal Mix',
                'jenis_kategori' => 'Rempah-Rempah/Herbal',
                'deskripsi' => 'Campuran benih rempah herbal untuk kesehatan.',
                'jumlah_biji' => 60,
                'berat_bersih' => '60gr',
                'stok' => 90,
                'harga' => 20000,
                'gambar' => 'herbal_mix.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Sayuran
            [
                'nama' => 'Benih Tomat',
                'jenis_kategori' => 'Sayuran',
                'deskripsi' => 'Benih tomat unggul, cocok untuk dataran rendah.',
                'jumlah_biji' => 30,
                'berat_bersih' => '30gr',
                'stok' => 100,
                'harga' => 12000,
                'gambar' => 'tomat.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Benih Bayam Hijau',
                'jenis_kategori' => 'Sayuran',
                'deskripsi' => 'Bayam hijau segar, mudah tumbuh.',
                'jumlah_biji' => 40,
                'berat_bersih' => '40gr',
                'stok' => 80,
                'harga' => 7000,
                'gambar' => 'bayam.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Benih Kangkung',
                'jenis_kategori' => 'Sayuran',
                'deskripsi' => 'Cepat panen, cocok untuk hidroponik.',
                'jumlah_biji' => 35,
                'berat_bersih' => '35gr',
                'stok' => 60,
                'harga' => 8000,
                'gambar' => 'kangkung.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Benih Wortel',
                'jenis_kategori' => 'Sayuran',
                'deskripsi' => 'Wortel oranye, cocok untuk dataran tinggi.',
                'jumlah_biji' => 25,
                'berat_bersih' => '25gr',
                'stok' => 50,
                'harga' => 10000,
                'gambar' => 'wortel.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Benih Sawi',
                'jenis_kategori' => 'Sayuran',
                'deskripsi' => 'Sawi hijau, cocok untuk tumisan.',
                'jumlah_biji' => 30,
                'berat_bersih' => '30gr',
                'stok' => 70,
                'harga' => 9000,
                'gambar' => 'sawi.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Buah-Buahan
            [
                'nama' => 'Benih Melon',
                'jenis_kategori' => 'Buah-Buahan',
                'deskripsi' => 'Benih melon manis, isi 20 butir.',
                'jumlah_biji' => 20,
                'berat_bersih' => '20gr',
                'stok' => 100,
                'harga' => 20000,
                'gambar' => 'melon.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Benih Semangka',
                'jenis_kategori' => 'Buah-Buahan',
                'deskripsi' => 'Semangka merah, segar dan manis.',
                'jumlah_biji' => 25,
                'berat_bersih' => '25gr',
                'stok' => 80,
                'harga' => 18000,
                'gambar' => 'semangka.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Benih Tomat Buah',
                'jenis_kategori' => 'Buah-Buahan',
                'deskripsi' => 'Tomat buah segar, hasil melimpah.',
                'jumlah_biji' => 30,
                'berat_bersih' => '30gr',
                'stok' => 60,
                'harga' => 12000,
                'gambar' => 'tomat_buah.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Benih Pepaya',
                'jenis_kategori' => 'Buah-Buahan',
                'deskripsi' => 'Pepaya California, mudah tumbuh.',
                'jumlah_biji' => 15,
                'berat_bersih' => '15gr',
                'stok' => 50,
                'harga' => 10000,
                'gambar' => 'pepaya.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Benih Anggur',
                'jenis_kategori' => 'Buah-Buahan',
                'deskripsi' => 'Benih anggur unggul, cocok untuk tabulampot.',
                'jumlah_biji' => 10,
                'berat_bersih' => '10gr',
                'stok' => 40,
                'harga' => 25000,
                'gambar' => 'anggur.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Bunga
            [
                'nama' => 'Benih Mawar Merah',
                'jenis_kategori' => 'Bunga',
                'deskripsi' => 'Benih mawar merah, cocok untuk taman.',
                'jumlah_biji' => 10,
                'berat_bersih' => '10gr',
                'stok' => 100,
                'harga' => 25000,
                'gambar' => 'mawar_merah.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Benih Melati',
                'jenis_kategori' => 'Bunga',
                'deskripsi' => 'Benih melati putih, harum dan segar.',
                'jumlah_biji' => 12,
                'berat_bersih' => '12gr',
                'stok' => 80,
                'harga' => 18000,
                'gambar' => 'melati.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Benih Anggrek',
                'jenis_kategori' => 'Bunga',
                'deskripsi' => 'Benih anggrek bulan, mudah tumbuh.',
                'jumlah_biji' => 8,
                'berat_bersih' => '8gr',
                'stok' => 60,
                'harga' => 25000,
                'gambar' => 'anggrek.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Benih Bunga Matahari',
                'jenis_kategori' => 'Bunga',
                'deskripsi' => 'Bunga matahari, cerah dan indah.',
                'jumlah_biji' => 20,
                'berat_bersih' => '20gr',
                'stok' => 70,
                'harga' => 15000,
                'gambar' => 'bunga_matahari.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Benih Tulip',
                'jenis_kategori' => 'Bunga',
                'deskripsi' => 'Benih tulip warna-warni, cocok untuk taman.',
                'jumlah_biji' => 15,
                'berat_bersih' => '15gr',
                'stok' => 50,
                'harga' => 22000,
                'gambar' => 'tulip.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tumbuhan
            [
                'nama' => 'Benih Pohon Mangga',
                'jenis_kategori' => 'Tumbuhan',
                'deskripsi' => 'Benih pohon mangga, tumbuh cepat.',
                'jumlah_biji' => 5,
                'berat_bersih' => '5gr',
                'stok' => 100,
                'harga' => 30000,
                'gambar' => 'mangga.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Benih Pohon Jambu',
                'jenis_kategori' => 'Tumbuhan',
                'deskripsi' => 'Benih pohon jambu air, segar dan manis.',
                'jumlah_biji' => 8,
                'berat_bersih' => '8gr',
                'stok' => 80,
                'harga' => 18000,
                'gambar' => 'jambu.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Benih Pohon Durian',
                'jenis_kategori' => 'Tumbuhan',
                'deskripsi' => 'Benih pohon durian unggul, cepat berbuah.',
                'jumlah_biji' => 3,
                'berat_bersih' => '3gr',
                'stok' => 60,
                'harga' => 50000,
                'gambar' => 'durian.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Benih Pohon Alpukat',
                'jenis_kategori' => 'Tumbuhan',
                'deskripsi' => 'Benih pohon alpukat, daging tebal.',
                'jumlah_biji' => 6,
                'berat_bersih' => '6gr',
                'stok' => 70,
                'harga' => 25000,
                'gambar' => 'alpukat.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Benih Pohon Rambutan',
                'jenis_kategori' => 'Tumbuhan',
                'deskripsi' => 'Benih pohon rambutan, manis dan segar.',
                'jumlah_biji' => 7,
                'berat_bersih' => '7gr',
                'stok' => 50,
                'harga' => 20000,
                'gambar' => 'rambutan.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
