<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\PlantTypes;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'product_name' => 'Tembakau Kemloko 2 (Dasar)',
                'plant_type_id' => 1, 
                'description' => 'Benih tembakau Kemloko 2 (Dasar) merupakan varietas unggulan yang dikenal memiliki aroma kuat dan cita rasa khas. Cocok ditanam di lahan tropis dengan ketinggian sedang hingga tinggi. Daunnya lebar dan tebal, ideal untuk produksi tembakau berkualitas tinggi. Varietas ini menunjukkan ketahanan yang baik terhadap beberapa penyakit umum pada tembakau dan memiliki potensi hasil panen yang memuaskan.',
                'minimum_stock' => 10,
                'stock' => 100,
                'unit' => 'Kg',
                'price_per_unit' => 25000,
                'minimum_purchase' => 5,
                'image1' => 'Tembakau Kemloko 2 (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Tembakau Kemloko 3 (Dasar)',
                'plant_type_id' => 1, 
                'description' => 'Varietas Tembakau Kemloko 3 (Dasar) adalah pilihan tepat untuk petani yang mencari kualitas dan kuantitas. Tanaman ini memiliki pertumbuhan yang cepat dan seragam, serta menghasilkan daun yang lebih banyak dibandingkan varietas Kemloko lainnya. Benih tembakau ini unggul, cocok untuk lahan tropis. Daunnya lebar dan tebal, sangat cocok untuk pembuatan rokok kretek. Memiliki ketahanan yang baik terhadap kekeringan dan dapat tumbuh optimal di berbagai kondisi tanah. Keunggulan utamanya adalah rasa dan aroma yang lebih lembut, menjadikannya favorit di pasar.',
                'minimum_stock' => 10,
                'stock' => 100,
                'unit' => 'Kg',
                'price_per_unit' => 25000,
                'minimum_purchase' => 5,
                'image1' => 'Tembakau Kemloko 3 (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Tembakau Bligon 1 (Dasar)',
                'plant_type_id' => 1, 
                'description' => 'Tembakau Bligon 1 (Dasar) dikenal karena ketahanannya yang luar biasa dan adaptasi yang baik terhadap iklim. Varietas ini menghasilkan daun dengan kandungan nikotin sedang, memberikan rasa seimbang yang disukai banyak konsumen. Benih tembakau ini sangat unggul untuk perkebunan di lahan tropis. Tanaman ini memiliki daun yang lebar dan tebal, sangat cocok untuk bahan baku rokok berkualitas. Selain itu, tembakau ini dikenal memiliki aroma yang harum dan cita rasa yang unik.',
                'minimum_stock' => 10,
                'stock' => 100,
                'unit' => 'Kg',
                'price_per_unit' => 25000,
                'minimum_purchase' => 5,
                'image1' => 'Tembakau Bligon 1 (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Tembakau H 382 T2 Agribun (Dasar)',
                'plant_type_id' => 1, 
                'description' => 'Tembakau H 382 T2 Agribun adalah varietas unggulan yang dikembangkan untuk menghasilkan daun dengan kualitas terbaik. Tembakau ini memiliki tekstur daun yang halus dan aroma yang ringan, cocok untuk tembakau linting atau rokok kretek mild. Tanaman ini tumbuh subur di dataran rendah dan menengah, serta memiliki ketahanan terhadap beberapa hama dan penyakit umum. Benih tembakau ini berkualitas tinggi dan cocok untuk industri rokok. Daunnya tipis dan lebar dengan kandungan nikotin rendah. Selain itu, tembakau ini juga memiliki ketahanan terhadap kekeringan.',
                'minimum_stock' => 5,
                'stock' => 80,
                'unit' => 'Kg',
                'price_per_unit' => 20000,
                'minimum_purchase' => 2,
                'image1' => 'Tembakau H 382 T2 Agribun (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Tembakau H 382 T4 Agribun (Dasar)',
                'plant_type_id' => 1, 
                'description' => 'Tembakau H 382 T4 Agribun adalah varietas tembakau yang dirancang untuk produktivitas tinggi. Varietas ini menghasilkan daun yang lebih tebal dan berbobot, menjadikannya pilihan ekonomis bagi petani. Benih tembakau ini memiliki potensi panen yang lebih tinggi, cocok untuk perkebunan dengan skala besar. Tanaman ini tumbuh dengan cepat dan memiliki daun lebar yang ideal untuk pengeringan. Aromanya yang kuat dan cita rasa yang khas menjadikannya pilihan populer di pasaran.',
                'minimum_stock' => 5,
                'stock' => 80,
                'unit' => 'Kg',
                'price_per_unit' => 20000,
                'minimum_purchase' => 2,
                'image1' => 'Tembakau H 382 T4 Agribun (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Tembakau H 382 T6 Agribun (Dasar)',
                'plant_type_id' => 1, 
                'description' => 'Tembakau H 382 T6 Agribun adalah varietas tembakau yang dikenal karena ketahanan unggulnya terhadap berbagai kondisi lingkungan ekstrem. Tanaman ini dapat tumbuh di tanah yang kurang subur dan tetap menghasilkan daun berkualitas. Benih tembakau ini memiliki daya tahan yang tinggi terhadap penyakit dan hama, sehingga sangat cocok untuk penanaman di berbagai daerah. Daunnya tebal dan kuat, memberikan hasil yang konsisten. Varietas ini dikenal dengan aroma uniknya yang cocok untuk campuran rokok kretek.',
                'minimum_stock' => 5,
                'stock' => 80,
                'unit' => 'Kg',
                'price_per_unit' => 20000,
                'minimum_purchase' => 2,
                'image1' => 'Tembakau H 382 T6 Agribun (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Tembakau Semaran Jahe (Dasar)',
                'plant_type_id' => 1, 
                'description' => 'Benih ini memiliki ciri khas aroma pedas seperti jahe, menjadikannya pilihan unik bagi para penggemar tembakau. Tanaman ini adaptif terhadap iklim dataran rendah, tumbuh cepat, dan menghasilkan daun dengan tekstur yang renyah setelah dikeringkan. Rasa dan aromanya yang kuat sangat cocok untuk dicampur dengan varietas tembakau lain untuk menciptakan blend yang unik.',
                'minimum_stock' => 8,
                'stock' => 60,
                'unit' => 'Kg',
                'price_per_unit' => 30000,
                'minimum_purchase' => 1,
                'image1' => 'Tembakau Semaran Jahe (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Tembakau Jepril 1 (Dasar)',
                'plant_type_id' => 1, 
                'description' => 'Tembakau Jepril 1 (Dasar) merupakan varietas yang sangat populer di kalangan petani karena kemudahannya dalam budidaya dan hasil panen yang melimpah. Benih tembakau ini sangat unggul dan cocok untuk perkebunan. Tanaman ini memiliki daun lebar dan pertumbuhan cepat. Tembakau ini memiliki aroma yang harum dan cita rasa yang manis, sehingga cocok untuk bahan baku rokok berkualitas. Kualitas daunnya yang konsisten membuatnya diminati oleh industri.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Tembakau Jepril 1 (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Tembakau Jinten Pak Pie 2 (Dasar)',
                'plant_type_id' => 1, 
                'description' => 'Benih tembakau ini adalah varietas unik dengan aroma khas seperti jintan. Tanaman ini menghasilkan daun yang lebih kecil namun memiliki kandungan minyak atsiri yang tinggi, memberikan cita rasa yang sangat intens. Sangat cocok untuk pasar niche atau campuran tembakau premium. Varietas ini juga dikenal karena ketahanannya terhadap hama tertentu.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Tembakau Jinten Pak Pie 2 (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Tembakau Bojonegoro 1 (Dasar)',
                'plant_type_id' => 1, 
                'description' => 'Tembakau Bojonegoro 1 (Dasar) adalah salah satu varietas tembakau terkemuka dari wilayah Bojonegoro. Benih tembakau ini sangat unggul dan cocok untuk perkebunan. Tanaman ini memiliki daun yang lebar dan tebal, cocok untuk bahan baku rokok kretek. Tembakau ini memiliki cita rasa yang kuat, menjadikannya pilihan favorit untuk rokok tradisional. Tumbuh optimal di tanah liat berpasir dan iklim panas.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Tembakau Bojonegoro 1 (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Tembakau Prancak 95 (Dasar)',
                'plant_type_id' => 1, 
                'description' => 'Tembakau Prancak 95 (Dasar) adalah varietas yang telah teruji dan populer sejak lama. Benih tembakau ini unggul untuk perkebunan di lahan tropis. Tanaman ini memiliki daun yang lebar dan tekstur yang tebal, menjadikannya ideal untuk industri rokok. Cita rasanya yang seimbang dan aromanya yang khas membuat tembakau ini sangat disukai. Varietas ini juga memiliki ketahanan yang baik terhadap penyakit layu bakteri.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Tembakau Prancak 95 (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Tembakau Kasturi 2 (Dasar)',
                'plant_type_id' => 1, 
                'description' => 'embakau Kasturi 2 (Dasar) dikenal dengan aromanya yang sangat kuat dan khas, mirip dengan kasturi. Benih tembakau ini sangat unggul dan cocok untuk perkebunan. Daunnya yang berukuran sedang memiliki kandungan minyak atsiri yang tinggi, menghasilkan rasa yang intens dan unik. Varietas ini sering digunakan sebagai bahan tambahan untuk meningkatkan aroma pada campuran tembakau lain.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Tembakau Kasturi 2 (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Kapas Kanesia 10 (Pokok)',
                'plant_type_id' => 2, 
                'description' => 'Kapas Kanesia 10 (Pokok) adalah varietas kapas unggulan yang dikembangkan untuk menghasilkan serat berkualitas tinggi. Benih kapas ini sangat unggul untuk perkebunan di berbagai daerah. Tanaman ini memiliki serat yang kuat dan putih bersih, ideal untuk industri tekstil. Selain itu, kapas ini memiliki ketahanan yang baik terhadap hama dan penyakit umum pada tanaman kapas, serta tumbuh subur di lahan kering.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Kapas Kanesia 10 (Pokok).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Kapas Kanesia 15 (Pokok)',
                'plant_type_id' => 2, 
                'description' => 'Kapas Kanesia 15 (Pokok) merupakan varietas kapas hibrida dengan produktivitas tinggi. Benih kapas ini sangat unggul untuk industri tekstil. Tanaman ini menghasilkan serat yang panjang dan halus. Selain itu, kapas ini memiliki ketahanan yang sangat baik terhadap hama, sehingga sangat cocok untuk perkebunan skala besar. Kualitas seratnya yang superior menjadikannya pilihan utama.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Kapas Kanesia 15 (Pokok).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Kapas Kanesia 16 (Dasar)',
                'plant_type_id' => 2, 
                'description' => 'Kapas Kanesia 16 (Dasar) adalah varietas yang dikenal karena ketahanan luar biasanya terhadap kekeringan. Benih kapas ini sangat unggul dan cocok untuk perkebunan di daerah kering. Tanaman ini menghasilkan serat kapas yang tebal dan kuat, ideal untuk produk tekstil yang membutuhkan daya tahan tinggi. Varietas ini juga memiliki tingkat produktivitas yang stabil.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Kapas Kanesia 16 (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Kapas Kanesia 17 (Dasar)',
                'plant_type_id' => 2, 
                'description' => 'Kapas Kanesia 17 (Dasar) adalah varietas kapas yang menghasilkan serat dengan kualitas premium. Benih kapas ini sangat unggul dan cocok untuk perkebunan. Seratnya sangat halus dan panjang, menjadikannya bahan baku ideal untuk kain berkualitas tinggi. Tanaman ini memiliki pertumbuhan yang cepat dan seragam, serta ketahanan yang baik terhadap serangan penyakit. Kualitas ini sangat diminati oleh produsen tekstil.Benih kapas ini sangat unggul dan cocok untuk perkebunan. Seratnya sangat halus dan panjang, menjadikannya bahan baku ideal untuk kain berkualitas tinggi. Tanaman ini memiliki pertumbuhan yang cepat dan seragam, serta ketahanan yang baik terhadap serangan penyakit. Kualitas ini sangat diminati oleh produsen tekstil.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Kapas Kanesia 17 (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Kapas Kanesia 18 (Dasar)',
                'plant_type_id' => 2, 
                'description' => 'Kapas Kanesia 18 (Dasar) menawarkan kombinasi unik antara produktivitas tinggi dan ketahanan yang kuat. Benih kapas ini sangat unggul untuk perkebunan. Tanaman ini menghasilkan serat kapas dengan panjang medium dan daya serap yang baik, cocok untuk berbagai aplikasi tekstil. Kapas ini juga memiliki ketahanan yang baik terhadap hama dan penyakit, menjadikannya pilihan yang andal untuk petani.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Kapas Kanesia 18 (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Kapas Kanesia 19 (Pokok)',
                'plant_type_id' => 2, 
                'description' => 'Kapas Kanesia 19 (Pokok) adalah varietas kapas yang dirancang untuk menghasilkan serat dengan kekuatan tarik luar biasa. Benih kapas ini sangat unggul untuk perkebunan di lahan tropis. Seratnya sangat kuat dan tidak mudah putus, ideal untuk benang dan kain yang membutuhkan durabilitas tinggi. Tanaman ini juga menunjukkan performa yang stabil di berbagai kondisi cuaca, memberikan hasil panen yang konsisten.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Kapas Kanesia 19 (Pokok).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Kapas Kanesia 20 (Dasar)',
                'plant_type_id' => 2, 
                'description' => 'Kapas Kanesia 20 (Dasar) dikenal dengan seratnya yang super putih dan bersih, tanpa banyak kotoran. Benih kapas ini sangat unggul dan cocok untuk perkebunan. Kualitas serat yang tinggi dan kemudahan pemrosesan menjadikan kapas ini sangat diminati di industri tekstil. Tanaman ini tumbuh dengan subur di dataran rendah hingga menengah dan memiliki potensi hasil panen yang sangat memuaskan.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Kapas Kanesia 20 (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Kapas Kanesia 21(Dasar)',
                'plant_type_id' => 2, 
                'description' => 'Kapas Kanesia 21 (Dasar) merupakan varietas kapas yang dirancang untuk efisiensi budidaya. Benih kapas ini sangat unggul dan cocok untuk perkebunan. Tanaman ini memiliki masa panen yang lebih singkat dan hasil panen yang lebih cepat, memaksimalkan rotasi tanam. Serat yang dihasilkan memiliki kualitas standar industri yang baik, cocok untuk berbagai kebutuhan produksi tekstil. Ini adalah pilihan yang sangat praktis bagi petani.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Kapas Kanesia 21(Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Kapas Kanesia 22(Dasar)',
                'plant_type_id' => 2, 
                'description' => 'Kapas Kanesia 22 (Dasar) adalah varietas kapas yang dikenal karena daya tahan dan adaptasinya di lahan marginal. Benih kapas ini sangat unggul dan cocok untuk perkebunan. Tanaman ini dapat tumbuh optimal di tanah yang kurang subur dan membutuhkan sedikit air. Seratnya yang dihasilkan memiliki kekuatan yang baik, menjadikannya pilihan ideal untuk daerah dengan sumber daya terbatas. Varietas ini sangat andal untuk kondisi pertanian yang menantang.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Kapas Kanesia 22(Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Wijen SBR 1 (Dasar)',
                'plant_type_id' => 3, 
                'description' => 'Wijen SBR 1 (Dasar) adalah varietas wijen unggul yang menghasilkan biji wijen berkualitas tinggi dengan kandungan minyak melimpah. Benih wijen ini sangat unggul untuk perkebunan. Tanaman ini memiliki biji yang besar, berwarna putih bersih, dan rasanya yang gurih. Wijen ini ideal untuk produksi minyak wijen, bahan baku makanan, maupun pakan ternak. Pertumbuhannya cepat dan produktivitasnya tinggi, menjadikannya pilihan yang sangat menguntungkan bagi petani.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Wijen SBR 1 (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Wijen SBR 1 (Pokok)',
                'plant_type_id' => 3, 
                'description' => 'Wijen SBR 1 (Pokok) merupakan varietas wijen pokok yang stabil dan andal. Benih wijen ini sangat unggul dan cocok untuk perkebunan di berbagai daerah. Tanaman ini menghasilkan biji wijen dengan kualitas premium dan tahan lama. Biji wijen ini memiliki kandungan minyak yang tinggi dan rasa yang sangat lezat, ideal untuk diolah menjadi minyak wijen atau ditambahkan ke hidangan. Selain itu, tanaman ini memiliki daya tahan yang baik terhadap hama dan penyakit.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Wijen SBR 1 (Pokok).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Wijen SBR 4 (Pokok)',
                'plant_type_id' => 3, 
                'description' => 'Wijen SBR 4 (Pokok) adalah varietas wijen unggul yang dikenal karena kemampuan adaptasinya yang luas. Benih wijen ini sangat unggul untuk perkebunan. Tanaman ini menghasilkan biji wijen yang besar dan berkualitas. Wijen ini dapat tumbuh subur di berbagai jenis tanah, termasuk lahan kering. Biji wijen ini memiliki kandungan minyak yang tinggi, menjadikannya ideal untuk industri minyak dan makanan. Produksi wijen SBR 4 (Pokok) juga stabil dan memberikan hasil yang memuaskan.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Wijen SBR 4 (Pokok).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Wijen WINAS 1 (Pokok)',
                'plant_type_id' => 3, 
                'description' => 'Wijen WINAS 1 (Pokok) adalah varietas wijen lokal yang dikembangkan untuk menghasilkan biji wijen dengan kualitas premium. Benih wijen ini sangat unggul untuk perkebunan. Biji wijen yang dihasilkan sangat besar dan memiliki warna cerah, cocok untuk ekspor. Kandungan minyak wijen ini juga sangat tinggi, sehingga sangat ideal untuk industri makanan. Tanaman ini tumbuh dengan cepat dan memiliki ketahanan yang baik terhadap hama dan penyakit, menjadikan pilihan yang sangat menguntungkan bagi petani.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Wijen WINAS 1 (Pokok).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Wijen WINAS 2 (Pokok)',
                'plant_type_id' => 3, 
                'description' => 'Wijen WINAS 2 (Pokok) dikenal dengan produktivitasnya yang sangat tinggi, cocok untuk petani yang ingin memaksimalkan hasil panen. Benih wijen ini sangat unggul untuk perkebunan. Biji wijen yang dihasilkan memiliki kualitas standar industri yang baik, menjadikannya ideal untuk berbagai kebutuhan. Tanaman ini memiliki masa panen yang lebih cepat dibandingkan varietas wijen lainnya, sehingga dapat memberikan keuntungan lebih bagi petani. Wijen ini juga memiliki ketahanan yang baik terhadap hama.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Wijen WINAS 2 (Pokok).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Wijen SBR 3 (Dasar)',
                'plant_type_id' => 3, 
                'description' => 'Benih wijen ini dikenal karena daya tahannya yang baik terhadap penyakit layu dan adaptasinya yang luas terhadap berbagai kondisi iklim. Biji wijen yang dihasilkan memiliki kualitas tinggi dengan kandungan minyak yang melimpah, menjadikannya pilihan ideal untuk produksi minyak wijen dan kebutuhan kuliner. Pertumbuhannya yang kuat dan hasil panen yang konsisten membuatnya menjadi pilihan populer di kalangan petani.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Wijen SBR 3 (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Rosela Herbal Roselindo 1 (Pokok)',
                'plant_type_id' => 2, 
                'description' => 'Benih rosela ini dikenal karena menghasilkan kelopak bunga berwarna merah cerah dengan kandungan vitamin C dan antioksidan yang sangat tinggi. Sangat cocok untuk diolah menjadi teh herbal, sirup, atau selai. Tanaman ini tumbuh dengan cepat dan memiliki ketahanan yang baik terhadap hama, serta mudah dibudidayakan di berbagai jenis tanah.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Rosela Herbal Roselindo 1 (Pokok).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Rosela Herbal Roselindo 2 (Dasar)',
                'plant_type_id' => 2, 
                'description' => 'Benih rosela ini unggul karena menghasilkan kelopak bunga dengan warna merah yang pekat dan rasa asam yang seimbang. Ideal untuk industri makanan dan minuman, serta produk kesehatan. Tanaman ini tumbuh dengan kokoh dan memiliki produktivitas tinggi, memberikan hasil panen yang melimpah. Selain itu, varietas ini dikenal karena ketahanannya terhadap penyakit tertentu.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Rosela Herbal Roselindo 2 (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Rosela Herbal Roselindo 3 (Dasar)',
                'plant_type_id' => 2, 
                'description' => 'Benih rosela ini dikenal karena menghasilkan kelopak bunga yang besar dan tebal, dengan kandungan nutrisi yang sangat baik. Sangat cocok untuk diolah menjadi minuman kesehatan atau suplemen. Tanaman ini memiliki pertumbuhan yang cepat dan adaptasi yang baik di berbagai jenis iklim. Varietas ini juga memiliki ketahanan yang baik terhadap hama dan penyakit.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Rosela Herbal Roselindo 3 (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Rosela Herbal Roselindo 4 (Dasar)',
                'plant_type_id' => 2, 
                'description' => 'Rosela Herbal Roselindo 4 (Dasar) adalah varietas rosela unggulan yang dikenal karena kandungan antioksidan alaminya yang sangat tinggi. Benih rosela ini sangat unggul untuk perkebunan. Kelopak bunga yang dihasilkan memiliki warna merah gelap dan rasa yang tajam, sangat cocok untuk produk-produk kesehatan. Tanaman ini tumbuh dengan subur di lahan tropis dan memiliki produktivitas yang stabil. Varietas ini sangat diminati oleh industri farmasi dan makanan kesehatan.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Rosela Herbal Roselindo 4 (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Kenaf KR 6 (Dasar)',
                'plant_type_id' => 4, 
                'description' => 'Benih kenaf ini unggul karena menghasilkan serat yang sangat kuat dan panjang, ideal untuk industri kertas, tali, dan tekstil. Tanaman ini tumbuh dengan cepat dan memiliki batang yang kokoh, serta ketahanan yang baik terhadap penyakit. Kenaf KR 6 (Dasar) juga dikenal karena kemudahannya dalam budidaya dan adaptasi yang baik di berbagai jenis tanah.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Kenaf KR 6 (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Kenaf KR 9 (Dasar)',
                'plant_type_id' => 4, 
                'description' => 'Kenaf KR 9 (Dasar) adalah varietas kenaf yang dikenal karena produktivitasnya yang sangat tinggi. Benih kenaf ini sangat unggul untuk perkebunan. Tanaman ini menghasilkan serat yang tebal dan kuat, ideal untuk bahan baku pembuatan kertas dan bahan bangunan. Kenaf KR 9 (Dasar) tumbuh cepat, mudah dibudidayakan, dan memiliki ketahanan yang baik terhadap hama. Varietas ini sangat menguntungkan bagi petani.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Kenaf KR 9 (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Kenaf KR 14 (Dasar)',
                'plant_type_id' => 4, 
                'description' => 'Benih kenaf ini dikenal karena menghasilkan serat dengan kualitas premium dan daya tahan yang luar biasa. Sangat cocok untuk industri tekstil dan bahan komposit. Tanaman ini tumbuh dengan kokoh dan memiliki produktivitas yang stabil. Selain itu, varietas ini memiliki ketahanan yang baik terhadap penyakit, menjadikannya pilihan yang andal untuk petani.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Kenaf KR 14 (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
            [
                'product_name' => 'Jarak Kepyar ASB 175 Agribun (Dasar)',
                'plant_type_id' => 5, 
                'description' => 'Benih jarak ini dikenal karena menghasilkan biji dengan kandungan minyak yang sangat tinggi, ideal untuk industri biodiesel, pelumas, dan produk kosmetik. Tanaman ini tumbuh dengan cepat, memiliki daya tahan yang baik terhadap kekeringan, dan dapat tumbuh optimal di lahan kering. Produktivitasnya yang tinggi menjadikannya pilihan yang sangat menguntungkan bagi petani.',
                'minimum_stock' => 3,
                'stock' => 40,
                'unit' => 'Kg',
                'price_per_unit' => 50000,
                'minimum_purchase' => 1,
                'image1' => 'Jarak Kepyar ASB 175 Agribun (Dasar).jpeg',
                // 'image2' => 'default2.jpeg',
                // 'image_certificate' => 'default_cert.jpeg',
            ],
        ];

        foreach ($products as $product) {
            Product::firstOrCreate(
                ['product_name' => $product['product_name']],
                array_merge($product, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
